### ISSUE TITLE
Parsing an OPDS 2.0 publication should be moved to r2-shared-swift

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/readium-opds-swift#13]
The title says it all: the ability to parse a publication using the OPDS 2.0 parser is incredibly useful (it works with Web Publications, audiobooks along with comics) and should be moved to the shared model.

This means the [following function](https://github.com/readium/readium-opds-swift/blob/master/readium-opds/OPDS2Parser.swift#L330) along with all the functions that are called by it.

**Comment by llemeurfr** [comment]
Is it still the case with the recent evolutions of the OPDS code?

**Comment by HadrienGardeur** [comment]
Yes it remains IMO a good idea to move the code for parsing publications in OPDS 2.0 to the shared repo.

This will be what we use as well for remote publications using the Readium Web Publication Manifest.

**Comment by gbugniot** [comment]
It will results in moving the following method:

- `static internal func parsePublication(pubDict: [String: Any]) throws`

- `static internal func parsePublicationMetadata(metadataDict: [String: Any]) throws -> Metadata`

- `static internal func parseContributors(_ contributors: Any) throws -> [Contributor]`

- `static internal func parseContributor(_ cDict: [String: Any]) throws -> Contributor`

- `static internal func parseCollection(_ collectionDict: [String: Any]) throws -> R2Shared.Collection`

- `static internal func parseLink(linkDict: [String: Any]) throws -> Link`

- `static internal func parseIndirectAcquisition(indirectAcquisitionDict: [String: Any]) throws -> IndirectAcquisition`

Also, what strategy should we adopt regarding this migration? I was thinking to move `parsePublication` to `Publication.swift` (R2Shared), `parsePublicationMetadata` to `Metadata.swift` (R2Shared) and so on..
