### ISSUE TITLE
Add helper method to handle OPDS 1.x/2.0 parsing

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/readium-opds-swift#16]
Right now, OPDS parsers are in their own classes and there's no helper method that can handle that easily for you.

We should be able to simply call `parse(URL)` and let the parser decide if it's 1.x or 2.0 on its own.

**Comment by HadrienGardeur** [comment]
Just a quick note then.

I looked at the current APIs and I saw that we have:
`public static func parseURL(url: URL) -> Promise<Feed>`

Since a URL could either return a Feed or a Publication, we might need to switch to something a little more generic that return a structure containing additional info, for example:

- HTTP response payload
- Feed or Publication
- String that identifies the OPDS version

The helper that handles the network request, along with sniffing the content type, should be in a more generic class, not tied to OPDS 1.x or 2.0.

**Comment by gbugniot** [comment]
What would be the best way for the parser to know if it's OPDS v1 (XML) or OPDS v2 (JSON)? 
Looking at content-type or trying to parse XML first and if it fails trying to parse JSON?

**Comment by HadrienGardeur** [comment]
Probably the second one. We can't expect the server to always handle media types properly.

**Comment by gbugniot** [comment]
@HadrienGardeur as you already said, parsing could return a `Feed` or a `Publication`. 

But `public static func parseURL(url: URL) -> Promise<Feed>` method can only returns a `Feed` for now. Its logic implementation is: If the parser find only a `Publication`, it will build a new `Feed` and then it will add the `Publication` to it.

Is this something to fix?

**Comment by HadrienGardeur** [comment]
Yes this should be fixed. We can't expect to always return a `Feed` and the same helper should work on `Publication` as well.

We need a structure on top of `Feed` and `Publication` that the client will be able to inspect. This should probably contain additional information, such as the HTTP payloads (request and response) or the URI that was fetched.

**Comment by aferditamuriqi** [comment]
closing this issue with this PR https://github.com/readium/r2-testapp-swift/pull/127
