### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-opds-swift#17]
The OPDS module will essentially be used as part of a R2 app. But developers may desire to use it from their own app. For that they need a clear description of how the module is to be used (dependencies, install, API), in the readme.

**Comment by HadrienGardeur** [comment]
IMO this should be handled after #16 for usage.

**Comment by aferditamuriqi** [comment]
https://github.com/readium/readium-opds-swift/pull/30
